run:
  name: baseline_rf
  output_dir: results
  random_state: 67

dataset:
  openml_name: Fashion-MNIST
  local_dir: data
  test_size: 0.2
  val_size: 0.2

model:
  type: random_forest
  n_estimators: 300
  max_depth: null
  min_samples_leaf: 1
  n_jobs: -1

preprocessing:
  scale: false
